### ISSUE TITLE
Passwort-Mechanismen aktualisieren

### ISSUE THREAD

**Issue by sgraewe** [ClanSphere/ClanSphere#31]

**Comment by TroaX** [comment]
Passwordhashes für den Benutzerteil aktualisiert. Forum, Clans/Teams/Squads etc. stehen noch aus.

**Comment by TroaX** [comment]
Bis auf die Foren werden die Passwörter für Teams sowieso nicht verschlüsselt. Die Forenpasswörter wurden jetzt fest auf sha1 gesetzt.
