### ISSUE TITLE
Wie kann ich Clansphere auf aktuelle Version upgraden

### ISSUE THREAD

**Issue by ghost** [ClanSphere/ClanSphere#45]
Hallo Webentwickler,

kann ich mich hier auf Deutsch äussern? Ich würde gerne meine Clansphere-Installation auf die Version aus 2014 upgraden. Wie kann ich das anstellen?

In den Infos meiner Installation steht noch etwas von Clansphere 2009. Ich glaube, dass es eine alte Version ist. Gibt es eine Möglichkeit, das uptograden und das im Browser oder via Konsole?

Danke im Vorfeld

**Comment by hajo-p** [comment]
Dafür am besten die SQL-Updates der Reihe nach ausführen über den Admin-Bereich und im Anschluss via FTP die neuen Dateien hochladen bzw. bestehende dabei ersetzen. Vorher ein Backup anzulegen von Datenbank und FTP-Inhalt bietet sich an, falls der Provider dies nicht automatisch erstellt bzw. verfügbar macht. Solange keine manuellen Änderungen an den PHP-Dateien oder eigene Datenbankerweiterungen vorgenommen worden sind, sollte danach noch alles laufen. Etwaige Zusatzmodule müssen im Anschluss eventuell ebenfalls aktualisiert werden, um (wieder) zu funktionieren.

**Comment by ghost** [comment]
Hallo @hajo-p ,
vielen Dank für deine rasche Hilfestellung und es klappte genau so wie du es beschrieben hast. Nun habe ich die vorletzte Clansphere Version, aber es steht im Backend immerhin, es sei aktuell. 

Eine Frage habe ich noch. Gibt es bei den News in Clansphere Beitragsbilder wie bei einem Blog? Artikelanleser leuchten mir ein, aber mit einem Thumbnail hinterlegt oder als grosses Beitragsbild auf der News-Startseite wäre es mal ideal. Vermutlich geht das gar nicht.

**Comment by hajo-p** [comment]
Ich weiß nicht, was mit Beitragsbildern gemeint ist, aber mit aktiviertem WYSIWYG-Editor lassen sich HTML-News verfassen und bearbeiten. Dafür stehen CKEditor und TinyMCE zur Auswahl.

Die Issue hier werde ich schließen, da das eigentliche Problem erledigt ist. Support geben wir eigentlich nur im Forum auf der ClanSphere-Website. DIe Issues hier sind für technische Fehlermeldungen und Wünsche gedacht.
